services:
  backend:
    build: ./backend
    container_name: weekbite-backend
    volumes:
      - db-data:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: weekbite-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:
